import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { builtinThemeCandidates } from '../shuffle';
import {
    inferThemeVariant,
    listThemeFiles,
    loadColorThemeFile,
    mergeThemeDocuments,
    parseJsonc,
    resolveThemePath
} from '../theme-file';

const repoRoot = path.resolve(__dirname, '..', '..');

describe('parseJsonc', () => {
    it('strips line and block comments and trailing commas', () => {
        const text = `\uFEFF{
            // line comment
            "a": 1, /* block
            comment */ "b": [1, 2, ],
            "c": { "d": true, },
        }`;
        expect(parseJsonc(text)).toEqual({ a: 1, b: [1, 2], c: { d: true } });
    });

    it('leaves comment-like and comma-like text inside strings alone', () => {
        const text = '{ "url": "https://example.com/*x*/", "s": "a,}", "q": "say \\"//hi\\"" }';
        expect(parseJsonc(text)).toEqual({ url: 'https://example.com/*x*/', s: 'a,}', q: 'say "//hi"' });
    });

    it('still rejects invalid JSON', () => {
        expect(() => parseJsonc('{ "a": }')).toThrow();
    });
});

describe('mergeThemeDocuments', () => {
    it('lets the including theme override colors and appends its token rules', () => {
        const merged = mergeThemeDocuments(
            {
                name: 'Base',
                colors: { 'editor.background': '#000000', 'editor.foreground': '#ffffff' },
                tokenColors: [{ scope: 'comment' }],
                semanticTokenColors: { variable: '#111111' },
                semanticHighlighting: true
            },
            {
                name: 'Child',
                include: './base.json',
                colors: { 'editor.background': '#101010' },
                tokenColors: [{ scope: 'string' }],
                semanticTokenColors: { function: '#222222' }
            }
        );

        expect(merged).toEqual({
            name: 'Child',
            colors: { 'editor.background': '#101010', 'editor.foreground': '#ffffff' },
            tokenColors: [{ scope: 'comment' }, { scope: 'string' }],
            semanticTokenColors: { variable: '#111111', function: '#222222' },
            semanticHighlighting: true
        });
    });
});

describe('loadColorThemeFile', () => {
    let dir: string;

    beforeAll(() => {
        dir = fs.mkdtempSync(path.join(os.tmpdir(), 'vibecolors-theme-'));
        fs.mkdirSync(path.join(dir, 'base'));
        fs.writeFileSync(path.join(dir, 'base', 'root.json'), JSON.stringify({
            colors: { 'editor.background': '#ffffff', 'editor.foreground': '#000000' },
            tokenColors: [{ scope: 'comment', settings: { foreground: '#888888' } }]
        }));
        fs.writeFileSync(path.join(dir, 'child.json'), `{
            // Generated by "Developer: Generate Color Theme From Current Settings"
            "name": "My Light",
            "include": "./base/root.json",
            "colors": { "editor.foreground": "#222222", },
        }`);
        fs.writeFileSync(path.join(dir, 'tm.json'), JSON.stringify({ name: 'Tm', tokenColors: './x.tmTheme' }));
        fs.writeFileSync(path.join(dir, 'legacy.json'), JSON.stringify({ name: 'Legacy', settings: [{ scope: 'string' }] }));
        fs.writeFileSync(path.join(dir, 'loop.json'), JSON.stringify({ include: './loop.json' }));
        fs.writeFileSync(path.join(dir, 'array.json'), '[1, 2]');
        fs.writeFileSync(path.join(dir, 'notes.txt'), 'not a theme');
    });

    afterAll(() => {
        fs.rmSync(dir, { recursive: true, force: true });
    });

    it('inlines included themes so the result is self-contained', async () => {
        const doc = await loadColorThemeFile(path.join(dir, 'child.json'));
        expect(doc.include).toBeUndefined();
        expect(doc.name).toBe('My Light');
        expect(doc.colors).toEqual({ 'editor.background': '#ffffff', 'editor.foreground': '#222222' });
        expect(doc.tokenColors).toEqual([{ scope: 'comment', settings: { foreground: '#888888' } }]);
        expect(inferThemeVariant(doc)).toBe('light');
    });

    it('drops token colors that point at external tmTheme files', async () => {
        const doc = await loadColorThemeFile(path.join(dir, 'tm.json'));
        expect(doc.tokenColors).toBeUndefined();
    });

    it('reads legacy `settings` rules as token colors', async () => {
        const doc = await loadColorThemeFile(path.join(dir, 'legacy.json'));
        expect(doc.tokenColors).toEqual([{ scope: 'string' }]);
        expect(doc.settings).toBeUndefined();
    });

    it('fails on include cycles, non-objects and missing files', async () => {
        await expect(loadColorThemeFile(path.join(dir, 'loop.json'))).rejects.toThrow(/too deep/);
        await expect(loadColorThemeFile(path.join(dir, 'array.json'))).rejects.toThrow(/JSON object/);
        await expect(loadColorThemeFile(path.join(dir, 'missing.json'))).rejects.toThrow();
    });

    it('expands a folder to its JSON files', async () => {
        const files = await listThemeFiles(dir);
        expect(files.map(f => path.basename(f))).toEqual(['array.json', 'child.json', 'legacy.json', 'loop.json', 'tm.json']);
        expect(await listThemeFiles(path.join(dir, 'child.json'))).toEqual([path.join(dir, 'child.json')]);
    });
});

describe('inferThemeVariant', () => {
    it('prefers the declared type', () => {
        expect(inferThemeVariant({ type: 'light', colors: { 'editor.background': '#000000' } })).toBe('light');
        expect(inferThemeVariant({ type: 'hc' })).toBe('dark');
        expect(inferThemeVariant({ type: 'hcLight' })).toBe('light');
    });

    it('falls back to the editor background brightness', () => {
        expect(inferThemeVariant({ colors: { 'editor.background': '#1e1e1e' } })).toBe('dark');
        expect(inferThemeVariant({ colors: { 'editor.background': '#fafafa' } })).toBe('light');
        expect(inferThemeVariant({ colors: { 'editor.background': '#fffe' } })).toBe('light');
        expect(inferThemeVariant({ colors: { 'editor.background': 'red' } })).toBeUndefined();
        expect(inferThemeVariant({})).toBeUndefined();
    });
});

describe('resolveThemePath', () => {
    const home = path.resolve('/home/me');
    const workspace = path.resolve('/work/project');

    it('expands ~, ${userHome} and ${workspaceFolder}', () => {
        expect(resolveThemePath('~/themes/a.json', home, undefined)).toBe(path.join(home, 'themes', 'a.json'));
        expect(resolveThemePath('${userHome}/a.json', home, undefined)).toBe(path.join(home, 'a.json'));
        expect(resolveThemePath('${workspaceFolder}/t.json', home, workspace)).toBe(path.join(workspace, 't.json'));
    });

    it('resolves relative paths against the workspace folder only when one is open', () => {
        expect(resolveThemePath('themes/t.json', home, workspace)).toBe(path.join(workspace, 'themes', 't.json'));
        expect(resolveThemePath('themes/t.json', home, undefined)).toBeUndefined();
        expect(resolveThemePath('${workspaceFolder}/t.json', home, undefined)).toBeUndefined();
    });

    it('does not expand ~ in the middle of a name', () => {
        expect(resolveThemePath('~backup/t.json', home, workspace)).toBe(path.join(workspace, '~backup', 't.json'));
    });
});

describe('shipped theme files', () => {
    const pkg = JSON.parse(fs.readFileSync(path.join(repoRoot, 'package.json'), 'utf8'));
    const contributed: Array<{ label: string; uiTheme: string; path: string; _watch?: boolean }> = pkg.contributes.themes;

    it('every static theme loads and is classified with its contributed variant', async () => {
        const candidates = builtinThemeCandidates(contributed, repoRoot);
        expect(candidates.length).toBeGreaterThanOrEqual(10);
        for (const candidate of candidates) {
            const doc = await loadColorThemeFile(candidate.path);
            expect(inferThemeVariant(doc), candidate.label).toBe(candidate.variant);
        }
    });

    it('lets VS Code hot-reload every generated theme file', () => {
        const generated = contributed.filter(t => /^VibeColors (Dynamic|Auto|Shuffle) /.test(t.label));
        expect(generated.map(t => t.label)).toContain('VibeColors Shuffle Dark');
        expect(generated.map(t => t.label)).toContain('VibeColors Shuffle Light');
        for (const theme of generated) {
            expect(theme._watch, theme.label).toBe(true);
            expect(fs.existsSync(path.join(repoRoot, theme.path)), theme.path).toBe(true);
        }
    });
});
